name: Tests

on:
    push:
        branches: ["main"]
        paths:
            - '*.php'
    pull_request:
        branches: ["main"]
        paths:
            - '*.php'
    workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: "shivammathur/setup-php@v2"
      with:
        php-version: '8.1'
        coverage: 'xdebug'

    - uses: "ramsey/composer-install@v2"

    - name: Run test suite
      run: vendor/bin/phpunit --coverage-clover=coverage.xml

    - uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
