name: Tests

on:
    push:
        branches: main
        paths:
            - '*.php'
    pull_request:
        branches: main
        paths:
            - '*.php'

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: "shivammathur/setup-php@v2"
      with:
        php-version: '8.1'

    - uses: "ramsey/composer-install@v2"

    - name: Run test suite
      run: composer run-script test
